### ISSUE TITLE
俳句情報の読み取り時、null落ちする

### ISSUE THREAD

**Issue by AsazuTaiga** [AsazuTaiga/Kuawase#1]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kuawase.kuawase, PID: 11637
    java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at com.kuawase.kuawase.screen.qrread.QRReadViewModel.onReadQRCode(QRReadViewModel.java:27)
        at com.kuawase.kuawase.screen.qrread.QRReadFragment$1.barcodeResult(QRReadFragment.java:74)
        at com.journeyapps.barcodescanner.DecoratedBarcodeView$WrappedCallback.barcodeResult(DecoratedBarcodeView.java:50)
        at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(BarcodeView.java:52)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

kukaiInput画面にて、kukaiInfoをmodelにキャッシュしているはずなのだが、`Objects.requireNonNull(kukaiInfo)`した際にクラッシュする。

**Comment by AsazuTaiga** [comment]
修正 2019.11.14
